# Generated by Django 5.1.4 on 2025-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='content/videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='content/videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='content/videos/'),
        ),
    ]
