# Generated by Django 5.1.4 on 2025-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_video_video_file_video_video_1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
    ]
