# Generated by Django 5.1.4 on 2025-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_video_original_video_file_alter_video_video_1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Erlaubte Bildformate: JPG, PNG, WEBP. Empfohlene Größe: 1280x720px.', null=True, upload_to='img/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
    ]
