# Generated by Django 5.1.4 on 2025-06-20 11:30

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_category_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/', validators=[content.models.validate_video_file]),
        ),
    ]
